In [1]:
#numPy array

In [2]:
mylist=[1,2,3]

In [3]:
import numpy as np

In [5]:
arr=np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [16]:
np.zeros(3)


array([0., 0., 0.])

In [18]:
np.zeros(3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.linspace(0,5,2)

array([0., 5.])

In [26]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5)

array([0.36103544, 0.97495411, 0.3241894 , 0.39202623, 0.65485439])

In [29]:
np.random.rand(5,3)

array([[0.49969516, 0.69040584, 0.86709299],
       [0.0971192 , 0.76820014, 0.78257661],
       [0.83982283, 0.65098596, 0.97470092],
       [0.92605431, 0.90437076, 0.74701558],
       [0.72718937, 0.48347536, 0.28068741]])

In [30]:
np.random.randint(1,100)

15

In [31]:
np.random.randint(1,100,5)

array([94, 11, 21, 87, 72])

In [32]:
arr=np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr=np.random.randint(0,50,10)

In [42]:
ranarr

array([48, 39, 40, 26, 37,  3, 24, 32, 15, 32])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.max()

np.int64(48)

In [39]:
arr.max()

np.int64(24)

In [40]:
np.max(arr)

np.int64(24)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[5:7]

array([5, 6])

In [49]:
#operation

In [52]:
arr=np.arange(1,10)

In [53]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr +arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
arr +3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [57]:
arr_copy=np.copy(arr*arr)

In [58]:
arr_copy

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
1/0

ZeroDivisionError: division by zero

In [61]:
np.max(arr)

TypeError: 'numpy.int64' object is not iterable