In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

np.float64(180616.43835616432)

In [7]:
model.predict([[5000]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [8]:
#Save Model To a File Using Python Pickle

In [9]:
import pickle

In [10]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [11]:
#Load Saved Model

In [12]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

In [14]:
mp.intercept_

np.float64(180616.43835616432)

In [15]:
mp.predict([[5000]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [16]:
#Save Trained Model Using joblib

In [19]:
import joblib

In [20]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [21]:
#Load Saved Model

In [22]:
mj = joblib.load('model_joblib')

In [23]:
mj.coef_

array([135.78767123])

In [24]:
mj.intercept_

np.float64(180616.43835616432)

In [25]:
mj.predict([[5000]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])